# Generated by Django 4.0.5 on 2022-07-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_orders_orderno'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('upi_id', models.CharField(max_length=25)),
            ],
        ),
    ]
